### ISSUE TITLE
The trained model file

### ISSUE THREAD

**Issue by YY2222222222** [WangWenhao0716/Attentive-WaveBlock#1]
Can you share the trained domain adaptation model file ?

**Comment by YY2222222222** [comment]
> Can you share the trained domain adaptation model file ?

**Comment by WangWenhao0716** [comment]
Please refer to the README to find the trained models.

**Comment by YY2222222222** [comment]
thank you&nbsp;



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WangWenhao0716/Attentive-WaveBlock"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月16日(星期五) 晚上11:34
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [WangWenhao0716/Attentive-WaveBlock] The trained model file (Issue #1)





 
Please refer to the README to find the trained models.
